language: elixir
elixir:
  - 1.4
  - 1.5
otp_release:
  - 17.4
  - 18.1
script:
  - "MIX_ENV=test mix do deps.get, compile, test"

notifications:
  webhooks: "https://www.travisbuddy.com/"
  on_success: never